// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace WKGameplayTags
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Gameplay_AbilityInputBlocked);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Mouse);
	
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gameplay_State_Invincible);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gameplay_State_IronBody);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gameplay_State_Dodging);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gameplay_State_Input_BlockMove);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gameplay_Condition_ResoluteCounterflow);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gameplay_Message_Damage_Hit);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gameplay_Message_Damage_BeHitEnd);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gameplay_Message_ShouldMove);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gameplay_Message_Attack_Detection);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gameplay_Message_InputWindow_ResoluteCounterflow_End);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gameplay_Event_BeHit);
	
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gameplay_Event_PerfectDodge);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gameplay_EventData_DodgeF);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gameplay_EventData_DodgeB);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gameplay_EventData_DodgeL);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gameplay_EventData_DodgeR);
	
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_DaSheng_Skill_Skill01);
	
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_WuKong_Skill_Charge);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_WuKong_Skill_ResoluteCounterflow);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_WuKong_Movement_Dodge);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_WuKong_Movement_PerfectDodge);
	
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Amount_StickEnergy);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Amount_BaseDamage);
	
	FGameplayTag FindTagByString(const FString& TagString, bool bMatchPartialString = false);
}